import sys


def binary_to_cxx_source(input_file, output_file, var_name):
    with open(input_file, "rb") as f:
        data = f.read()
        size = len(data)
    with open(output_file, "w") as f:
        f.write("// Auto-generated by convert-bin.py\n")
        f.write(
            "#include <cstdint>\nnamespace binary_resource{\nusing namespace std;\n"
        )
        f.write("extern const uint8_t " + var_name + "_data[] = {")
        f.write(", ".join("{:d}".format(b) for b in data))
        f.write("};\n")
        f.write("extern const size_t " + var_name + "_size = " + str(size) + ";")
        f.write("}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python convert-bin.py <input_file> <output_file> <var_name>")
        sys.exit(1)
    binary_to_cxx_source(sys.argv[1], sys.argv[2], sys.argv[3])
